Add spectrum module
PAHdb/AmesPAHdbPythonSuite pull request #9
Opened 2021-12-07 14:11 UTC by alexmaragko

- Spectrum module and tests added. 
- Mock fitted.py module added.
- Example galaxy spectrum for fitting usage added in the resources directory.

2021-12-09 18:03 UTC, PAHdb requested changes

2021-12-09 18:03 UTC, PAHdb commented on amespahdbpythonsuite/spectrum.py
> +        Transitions.set(self, d, **keywords)
This line probably doesn't need to be here when line 36 is moved out of the nested if-statements.

2021-12-09 18:03 UTC, PAHdb commented on amespahdbpythonsuite/spectrum.py
> +                Transitions.set(self, d, **keywords)
Remove line 26 and indent this line out of the nested if-statements.

2021-12-09 18:03 UTC, PAHdb commented on amespahdbpythonsuite/spectrum.py
> +    def subdatabase(self, uids):
This method is not needed.

2021-12-09 18:03 UTC, PAHdb commented on amespahdbpythonsuite/spectrum.py
> +                      pahdb=self.subdatabase(uids),
Passing self.pahdb is sufficient here--its done by reference, so this wouldn't take up any additional memory.

2021-12-09 18:03 UTC, PAHdb commented on amespahdbpythonsuite/tests/test_spectrum.py
> +class TestSpecies():
Class name should probably be TestSpectrum?

2021-12-09 18:03 UTC, PAHdb commented on amespahdbpythonsuite/tests/test_spectrum.py
> +        monkeypatch.setattr(plt, 'show', lambda: None)
Didn't know about monkeypatch-pretty cool!

2021-12-10 06:36 UTC, alexmaragko commented
Updated to address the PR comments.

2021-12-13 16:12 UTC, PAHdb approved these changes

2021-12-13 16:13 UTC, merged